import { auth } from "@/auth"
import { NextResponse } from "next/server"

export default auth((req) => {
    const { nextUrl, auth: session } = req
    const pathname = nextUrl.pathname

    // Routes that completely bypass middleware (static assets, API, etc.)
    const bypassRoutes = [
        '/api',
        '/_next',
        '/favicon.ico',
        '/opengraph-image',
    ]

    // Check if current path should bypass middleware
    const shouldBypass = bypassRoutes.some(route =>
        pathname === route || pathname.startsWith(route + '/')
    ) || pathname.match(/\.(jpg|jpeg|png|gif|svg|ico|webp|mp4|webm)$/)

    if (shouldBypass) {
        return NextResponse.next()
    }

    // Public routes - anyone can access, no onboarding check needed
    // These are content consumption routes
    const publicRoutes = [
        '/',              // Homepage
        '/login',         // Auth pages
        '/welcome',       // Onboarding page itself
        '/truyen',        // Novel pages & chapters
        '/tim-kiem',      // Search
    ]

    const isPublicRoute = publicRoutes.some(route =>
        pathname === route || pathname.startsWith(route + '/')
    )

    // Protected routes - require authentication AND completed onboarding
    // These are user-specific features that need a profile
    const protectedRoutes = [
        '/dashboard',     // User/Translator dashboard
        '/tu-truyen',     // User's library
        '/admin',         // Admin panel
        '/u/',            // User profile pages (except viewing other profiles)
    ]

    const isProtectedRoute = protectedRoutes.some(route =>
        pathname === route || pathname.startsWith(route)
    )

    // For public routes, always allow access (no onboarding redirect)
    if (isPublicRoute) {
        return NextResponse.next()
    }

    // For protected routes, check if user needs onboarding
    if (isProtectedRoute && session?.user) {
        const username = session.user.username
        const email = session.user.email

        // Check if username is null/empty OR matches auto-generated pattern
        const needsOnboarding = !username || (email && isAutoGeneratedUsername(username, email))

        if (needsOnboarding && pathname !== '/welcome') {
            // Redirect to welcome/onboarding page
            return NextResponse.redirect(new URL('/welcome', nextUrl.origin))
        }
    }

    // For all other routes, allow access
    return NextResponse.next()
})

/**
 * Check if a username is auto-generated (not custom-set by user)
 * Auto-generated pattern: emailPrefix OR emailPrefix_XXXX (4 random digits)
 */
function isAutoGeneratedUsername(username: string, email: string): boolean {
    const emailPrefix = email.split('@')[0].replace(/[^a-zA-Z0-9_]/g, '')

    // Exact match with email prefix
    if (username === emailPrefix) return true

    // Match pattern: emailPrefix_XXXX (4 digits)
    if (
        username.startsWith(emailPrefix + "_") &&
        username.length === emailPrefix.length + 5 &&
        /^\d{4}$/.test(username.slice(-4))
    ) {
        return true
    }

    return false
}

export const config = {
    // Run middleware on all routes except static files
    matcher: ["/((?!api|_next/static|_next/image|favicon.ico).*)"],
}

