"use client";

import { useState, useEffect, useCallback } from "react";
import { useSession } from "next-auth/react";
import { useRouter } from "next/navigation";
import { updateProfile, checkUsernameAvailability } from "@/actions/user";
import ImageUpload from "@/components/novel/image-upload";
import { Save, User, AtSign, Loader2, CheckCircle2, XCircle, Sparkles } from "lucide-react";

export default function WelcomePage() {
    const { data: session, status, update } = useSession();
    const router = useRouter();
    const [isLoading, setIsLoading] = useState(false);
    const [error, setError] = useState("");
    const [success, setSuccess] = useState("");

    const [nickname, setNickname] = useState("");
    const [username, setUsername] = useState("");
    const [image, setImage] = useState("");

    const [isCheckingUsername, setIsCheckingUsername] = useState(false);
    const [usernameAvailable, setUsernameAvailable] = useState<boolean | null>(null);
    const [usernameMessage, setUsernameMessage] = useState("");

    // Redirect if not authenticated or already has custom username
    useEffect(() => {
        if (status === "unauthenticated") {
            router.push("/login");
            return;
        }

        if (session?.user) {
            // Pre-fill with current values
            setNickname(session.user.nickname || session.user.name || "");
            setUsername(session.user.username || "");
            setImage(session.user.image || "");

            // Check if user already has a custom username (not auto-generated)
            if (session.user.email && session.user.username) {
                const emailPrefix = session.user.email.split('@')[0].replace(/[^a-zA-Z0-9_]/g, '');
                const currentUsername = session.user.username;

                const isAutoGenerated = currentUsername === emailPrefix ||
                    (currentUsername.startsWith(emailPrefix + "_") &&
                        currentUsername.length === emailPrefix.length + 5 &&
                        /^\d{4}$/.test(currentUsername.slice(-4)));

                // If already has custom username, redirect to home
                if (!isAutoGenerated) {
                    router.push("/");
                }
            }
        }
    }, [session, status, router]);

    // Debounce username check
    useEffect(() => {
        const checkUsername = async () => {
            if (!username || username === session?.user?.username) {
                setUsernameAvailable(null);
                setUsernameMessage("");
                return;
            }

            if (username.length < 3) {
                setUsernameAvailable(false);
                setUsernameMessage("Định danh phải có ít nhất 3 ký tự");
                return;
            }

            if (!/^[a-zA-Z0-9_]+$/.test(username)) {
                setUsernameAvailable(false);
                setUsernameMessage("Chỉ cho phép chữ cái, số và dấu gạch dưới");
                return;
            }

            setIsCheckingUsername(true);
            const isAvailable = await checkUsernameAvailability(username);
            setIsCheckingUsername(false);
            setUsernameAvailable(isAvailable);
            setUsernameMessage(isAvailable ? "Định danh khả dụng!" : "Định danh đã được sử dụng");
        };

        const timeoutId = setTimeout(checkUsername, 500);
        return () => clearTimeout(timeoutId);
    }, [username, session?.user?.username]);

    async function handleSubmit(e: React.FormEvent<HTMLFormElement>) {
        e.preventDefault();
        setIsLoading(true);
        setError("");
        setSuccess("");

        // Validate username is set and available
        if (!username || username.length < 3) {
            setError("Vui lòng chọn định danh hợp lệ (ít nhất 3 ký tự)");
            setIsLoading(false);
            return;
        }

        if (usernameAvailable === false && username !== session?.user?.username) {
            setError("Vui lòng chọn một định danh khả dụng");
            setIsLoading(false);
            return;
        }

        const result = await updateProfile({ nickname: nickname || undefined, image: image || undefined, username });

        if (result.error) {
            setError(result.error);
            setIsLoading(false);
        } else if (result.success) {
            setSuccess("Chào mừng bạn đến với Novest!");
            await update(); // Refresh session with new data

            // Redirect to home after a brief delay
            setTimeout(() => {
                router.push("/");
            }, 1500);
        }
    }

    if (status === "loading") {
        return (
            <div className="min-h-screen flex items-center justify-center bg-[#0B0C10]">
                <Loader2 className="w-8 h-8 text-amber-500 animate-spin" />
            </div>
        );
    }

    if (!session) return null;

    return (
        <div className="min-h-screen bg-[#0B0C10] text-slate-200 font-sans selection:bg-amber-500/30 flex items-center justify-center px-4">
            {/* Background Effects */}
            <div className="fixed inset-0 pointer-events-none overflow-hidden">
                <div className="absolute top-0 left-1/4 w-96 h-96 bg-amber-500/10 rounded-full blur-3xl animate-pulse" />
                <div className="absolute bottom-0 right-1/4 w-96 h-96 bg-emerald-500/10 rounded-full blur-3xl animate-pulse" />
            </div>

            <div className="w-full max-w-xl relative z-10">
                {/* Welcome Header */}
                <div className="text-center mb-8">
                    <div className="inline-flex items-center justify-center w-20 h-20 bg-linear-to-br from-amber-500 to-amber-600 rounded-2xl shadow-lg shadow-amber-500/30 mb-6">
                        <Sparkles className="w-10 h-10 text-white" />
                    </div>
                    <h1 className="text-4xl font-bold text-transparent bg-clip-text bg-linear-to-r from-amber-200 to-amber-500 mb-3">
                        Chào mừng Đạo Hữu!
                    </h1>
                    <p className="text-slate-400 text-lg">
                        Hãy thiết lập danh tính của bạn trong thế giới Novest
                    </p>
                </div>

                {/* Main Card */}
                <div className="bg-slate-900/50 backdrop-blur-sm border border-white/5 rounded-2xl p-8 shadow-2xl relative overflow-hidden">
                    <div className="absolute top-0 left-0 w-full h-1 bg-linear-to-r from-transparent via-amber-500 to-transparent opacity-50" />

                    <form onSubmit={handleSubmit} className="space-y-8">
                        {/* Messages */}
                        {error && (
                            <div className="bg-red-500/10 border border-red-500/20 text-red-400 px-4 py-3 rounded-lg text-sm flex items-center gap-2">
                                <XCircle className="w-4 h-4 shrink-0" /> {error}
                            </div>
                        )}
                        {success && (
                            <div className="bg-emerald-500/10 border border-emerald-500/20 text-emerald-400 px-4 py-3 rounded-lg text-sm flex items-center gap-2">
                                <CheckCircle2 className="w-4 h-4 shrink-0" /> {success}
                            </div>
                        )}

                        {/* Avatar Section */}
                        <div className="flex flex-col sm:flex-row gap-6 items-center sm:items-start pb-6 border-b border-white/5">
                            <div className="relative">
                                <ImageUpload
                                    value={image}
                                    onChange={setImage}
                                    disabled={isLoading}
                                    variant="avatar"
                                />
                            </div>
                            <div className="space-y-1 text-center sm:text-left">
                                <h3 className="text-lg font-medium text-slate-200">Ảnh Đại Diện</h3>
                                <p className="text-sm text-slate-500">
                                    Tùy chọn. Bạn có thể thêm sau.
                                </p>
                            </div>
                        </div>

                        {/* Identity Section */}
                        <div className="space-y-6">
                            {/* Nickname */}
                            <div className="space-y-2">
                                <label htmlFor="nickname" className="block text-sm font-medium text-slate-300">
                                    Biệt Danh <span className="text-slate-500">(tùy chọn)</span>
                                </label>
                                <div className="flex items-center bg-slate-950/50 border border-white/10 rounded-lg focus-within:border-amber-500/50 focus-within:ring-1 focus-within:ring-amber-500/50 transition-all">
                                    <div className="pl-3 flex items-center justify-center">
                                        <User className="w-4 h-4 text-slate-500 pointer-events-none" />
                                    </div>
                                    <input
                                        id="nickname"
                                        type="text"
                                        value={nickname}
                                        onChange={(e) => setNickname(e.target.value)}
                                        disabled={isLoading}
                                        className="w-full bg-transparent border-none py-2.5 pl-3 pr-4 text-slate-200 focus:ring-0 placeholder:text-slate-600"
                                        placeholder="Vị Đạo Hữu Vô Danh"
                                    />
                                </div>
                                <p className="text-xs text-slate-500">
                                    Tên hiển thị trên bình luận và trang cá nhân
                                </p>
                            </div>

                            {/* Username (Required) */}
                            <div className="space-y-2">
                                <label htmlFor="username" className="block text-sm font-medium text-slate-300">
                                    Định Danh <span className="text-amber-500">*</span>
                                </label>
                                <div className={`flex items-center bg-slate-950/50 border rounded-lg transition-all relative ${usernameAvailable === true ? "border-emerald-500/50 focus-within:border-emerald-500 focus-within:ring-1 focus-within:ring-emerald-500/20" :
                                    usernameAvailable === false ? "border-red-500/50 focus-within:border-red-500 focus-within:ring-1 focus-within:ring-red-500/20" :
                                        "border-white/10 focus-within:border-amber-500/50 focus-within:ring-1 focus-within:ring-amber-500/50"
                                    }`}>
                                    <div className="pl-3 flex items-center justify-center">
                                        <AtSign className="w-4 h-4 text-slate-500 pointer-events-none" />
                                    </div>
                                    <input
                                        id="username"
                                        type="text"
                                        value={username}
                                        onChange={(e) => setUsername(e.target.value.toLowerCase())}
                                        disabled={isLoading}
                                        className="w-full bg-transparent border-none py-2.5 pl-3 pr-10 text-slate-200 focus:ring-0 placeholder:text-slate-600"
                                        placeholder="dao_huu_123"
                                    />
                                    <div className="absolute right-3 top-1/2 -translate-y-1/2 flex items-center pointer-events-none">
                                        {isCheckingUsername && (
                                            <Loader2 className="w-4 h-4 text-amber-500 animate-spin" />
                                        )}
                                        {!isCheckingUsername && usernameAvailable === true && (
                                            <CheckCircle2 className="w-4 h-4 text-emerald-500" />
                                        )}
                                        {!isCheckingUsername && usernameAvailable === false && (
                                            <XCircle className="w-4 h-4 text-red-500" />
                                        )}
                                    </div>
                                </div>
                                <div className="flex justify-between items-start gap-2">
                                    <p className={`text-xs transition-colors ${usernameAvailable === true ? "text-emerald-400" :
                                        usernameAvailable === false ? "text-red-400" :
                                            "text-slate-500"
                                        }`}>
                                        {usernameMessage || "Định danh dùng cho URL trang cá nhân. Không thể thay đổi sau này!"}
                                    </p>
                                    <span className="text-xs text-slate-600 font-sans shrink-0">
                                        novest.com/u/{username || "..."}
                                    </span>
                                </div>
                            </div>
                        </div>

                        {/* Submit Button */}
                        <button
                            type="submit"
                            disabled={isLoading || !username || usernameAvailable === false}
                            className="w-full bg-linear-to-r from-amber-600 to-amber-500 hover:from-amber-500 hover:to-amber-400 text-slate-950 font-bold py-3 px-6 rounded-lg shadow-lg shadow-amber-500/20 transition-all active:scale-98 disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-2"
                        >
                            {isLoading ? <Loader2 className="w-5 h-5 animate-spin" /> : <Save className="w-5 h-5" />}
                            {isLoading ? "Đang lưu..." : "Bắt đầu hành trình"}
                        </button>

                        <p className="text-center text-xs text-slate-600">
                            Bằng việc tiếp tục, bạn đồng ý với Điều khoản sử dụng của Novest
                        </p>
                    </form>
                </div>
            </div>
        </div>
    );
}
