"use client";

import { useState, useEffect } from "react";
import { useSession } from "next-auth/react";
import { useRouter } from "next/navigation";
import { updateProfile, checkUsernameAvailability, getUserBirthday } from "@/actions/user";
import ImageUpload from "@/components/novel/image-upload";
import Link from "next/link";
import { ArrowLeft, Save, User, AtSign, Loader2, CheckCircle2, XCircle } from "lucide-react";

export default function SettingsPage() {
    const { data: session, status, update } = useSession();
    const router = useRouter();
    const [isLoading, setIsLoading] = useState(false);
    const [error, setError] = useState("");
    const [success, setSuccess] = useState("");

    const [nickname, setNickname] = useState("");
    const [username, setUsername] = useState("");
    const [image, setImage] = useState("");

    const [isCheckingUsername, setIsCheckingUsername] = useState(false);
    const [usernameAvailable, setUsernameAvailable] = useState<boolean | null>(null);
    const [usernameMessage, setUsernameMessage] = useState("");
    const [showWelcome, setShowWelcome] = useState(false);
    const [isUsernameLocked, setIsUsernameLocked] = useState(false);

    // Birthday state
    const [birthDay, setBirthDay] = useState<string>("");
    const [birthMonth, setBirthMonth] = useState<string>("");
    const [birthYear, setBirthYear] = useState<string>("");
    const [isBirthdayLocked, setIsBirthdayLocked] = useState(false);
    const [savedBirthday, setSavedBirthday] = useState<Date | null>(null);

    useEffect(() => {
        if (status === "unauthenticated") {
            router.push("/login");
        }

        if (session?.user) {
            setNickname(session.user.nickname || "");
            setUsername(session.user.username || "");
            setImage(session.user.image || "");

            // Check if username is locked (custom-set vs auto-generated)
            // Auto-generated pattern: emailPrefix or emailPrefix_XXXX (4 digits)
            if (session.user.email && session.user.username) {
                const emailPrefix = session.user.email.split('@')[0].replace(/[^a-zA-Z0-9_]/g, '');
                const currentUsername = session.user.username;

                // Check if it's still the auto-generated username
                const isAutoGenerated = currentUsername === emailPrefix ||
                    (currentUsername.startsWith(emailPrefix + "_") &&
                        currentUsername.length === emailPrefix.length + 5 &&
                        /^\d{4}$/.test(currentUsername.slice(-4)));

                setIsUsernameLocked(!isAutoGenerated);
            }

            // Fetch birthday to check if locked
            getUserBirthday().then((birthday) => {
                if (birthday) {
                    setIsBirthdayLocked(true);
                    setSavedBirthday(birthday);
                    // Pre-fill the values
                    const bd = new Date(birthday);
                    setBirthDay(String(bd.getDate()).padStart(2, '0'));
                    setBirthMonth(String(bd.getMonth() + 1).padStart(2, '0'));
                    setBirthYear(String(bd.getFullYear()));
                }
            });
        }

        // Check for welcome param
        const params = new URLSearchParams(window.location.search);
        if (params.get("welcome") === "true") {
            setShowWelcome(true);
        }
    }, [session, status, router]);

    // Debounce username check
    useEffect(() => {
        const checkUsername = async () => {
            if (!username || username === session?.user?.username) {
                setUsernameAvailable(null);
                setUsernameMessage("");
                return;
            }

            if (username.length < 3) {
                setUsernameAvailable(false);
                setUsernameMessage("Username must be at least 3 characters");
                return;
            }

            if (!/^[a-zA-Z0-9_]+$/.test(username)) {
                setUsernameAvailable(false);
                setUsernameMessage("Only letters, numbers, and underscores allowed");
                return;
            }

            setIsCheckingUsername(true);
            const isAvailable = await checkUsernameAvailability(username);
            setIsCheckingUsername(false);
            setUsernameAvailable(isAvailable);
            setUsernameMessage(isAvailable ? "Username is available" : "Username is already taken");
        };

        const timeoutId = setTimeout(checkUsername, 500);
        return () => clearTimeout(timeoutId);
    }, [username, session?.user?.username]);

    async function handleSubmit(e: React.FormEvent<HTMLFormElement>) {
        e.preventDefault();
        setIsLoading(true);
        setError("");
        setSuccess("");

        if (usernameAvailable === false && username !== session?.user?.username) {
            setError("Please choose a valid available username");
            setIsLoading(false);
            return;
        }

        // Build birthday string if all parts are selected
        const birthday = birthYear && birthMonth && birthDay
            ? `${birthYear}-${birthMonth}-${birthDay}`
            : undefined;

        const result = await updateProfile({ nickname, image, username, birthday });

        if (result.error) {
            setError(result.error);
            setIsLoading(false);
        } else if (result.success) {
            setSuccess(result.success);
            setIsLoading(false);
            // Pass updated data to trigger JWT callback to refresh session
            await update({
                user: {
                    nickname,
                    username,
                    image,
                }
            });
            // Redirect to new username path if username changed
            if (username !== session?.user?.username) {
                router.push(`/u/${username}/settings`);
            } else {
                router.refresh();
            }
        }
    }

    if (status === "loading") {
        return (
            <div className="min-h-screen flex items-center justify-center bg-[#0B0C10]">
                <Loader2 className="w-8 h-8 text-amber-500 animate-spin" />
            </div>
        );
    }

    if (!session) return null;

    const backLink = session.user.role === "ADMIN" || session.user.role === "TRANSLATOR" ? "/studio" : "/";

    return (
        <div className="min-h-screen bg-[#0B0C10] text-slate-200 font-sans selection:bg-amber-500/30">
            {/* Background Effects */}
            <div className="fixed inset-0 pointer-events-none overflow-hidden">
                <div className="absolute top-0 left-1/4 w-96 h-96 bg-amber-500/5 rounded-full blur-3xl" />
                <div className="absolute bottom-0 right-1/4 w-96 h-96 bg-emerald-500/5 rounded-full blur-3xl" />
            </div>

            <div className="max-w-3xl mx-auto px-6 py-12 relative z-10">
                {/* Header */}
                <div className="mb-10">
                    <Link
                        href={backLink}
                        className="inline-flex items-center gap-2 text-sm text-slate-400 hover:text-amber-400 transition-colors mb-6 group"
                    >
                        <ArrowLeft className="w-4 h-4 group-hover:-translate-x-1 transition-transform" />
                        Trở về
                    </Link>
                    <h1 className="text-4xl font-bold text-transparent bg-clip-text bg-linear-to-r from-amber-200 to-amber-500 mb-2">
                        Thiết Lập Hồ Sơ
                    </h1>
                    <p className="text-slate-400">
                        Quản lý danh tính của bạn trong thế giới Novest.
                    </p>
                </div>

                {/* Main Card */}
                <div className="bg-slate-900/50 backdrop-blur-sm border border-white/5 rounded-2xl p-8 shadow-2xl relative overflow-hidden">
                    <div className="absolute top-0 left-0 w-full h-1 bg-linear-to-r from-transparent via-amber-500/50 to-transparent opacity-50" />

                    <form onSubmit={handleSubmit} className="space-y-8">
                        {/* Messages */}
                        {error && (
                            <div className="bg-red-500/10 border border-red-500/20 text-red-400 px-4 py-3 rounded-lg text-sm flex items-center gap-2">
                                <XCircle className="w-4 h-4" /> {error}
                            </div>
                        )}
                        {success && (
                            <div className="bg-emerald-500/10 border border-emerald-500/20 text-emerald-400 px-4 py-3 rounded-lg text-sm flex items-center gap-2">
                                <CheckCircle2 className="w-4 h-4" /> {success}
                            </div>
                        )}

                        {/* Avatar Section */}
                        <div className="flex flex-col sm:flex-row gap-8 items-start sm:items-center pb-8 border-b border-white/5">
                            <div className="relative group">
                                <div className="relative">
                                    <ImageUpload
                                        value={image}
                                        onChange={setImage}
                                        disabled={isLoading}
                                        variant="avatar"
                                    />
                                </div>
                            </div>
                            <div className="space-y-1">
                                <h3 className="text-lg font-medium text-slate-200">Ảnh Đại Diện</h3>
                                <p className="text-sm text-slate-500">
                                    Định dạng JPG, PNG hoặc GIF. Tối đa 4MB.<br />
                                    Hãy chọn một hình ảnh thể hiện khí chất của bạn.
                                </p>
                            </div>
                        </div>

                        {/* Identity Section */}
                        <div className="space-y-6">
                            {/* Nickname */}
                            <div className="space-y-2">
                                <label htmlFor="nickname" className="block text-sm font-medium text-slate-300">
                                    Biệt Danh (Display Name)
                                </label>
                                <div className="flex items-center bg-slate-950/50 border border-white/10 rounded-lg focus-within:border-amber-500/50 focus-within:ring-1 focus-within:ring-amber-500/50 transition-all">
                                    <div className="pl-3 flex items-center justify-center">
                                        <User className="w-4 h-4 text-slate-500 pointer-events-none" />
                                    </div>
                                    <input
                                        id="nickname"
                                        type="text"
                                        value={nickname}
                                        onChange={(e) => setNickname(e.target.value)}
                                        disabled={isLoading}
                                        className="w-full bg-transparent border-none py-2.5 pl-3 pr-4 text-slate-200 focus:ring-0 placeholder:text-slate-600"
                                        placeholder="Vị Đạo Hữu Vô Danh"
                                    />
                                </div>
                                <p className="text-xs text-slate-500">
                                    Tên này sẽ hiển thị trên các bình luận và trang cá nhân của bạn.
                                </p>
                            </div>

                            {/* Username */}
                            <div className="space-y-2">
                                <label htmlFor="username" className="block text-sm font-medium text-slate-300">
                                    Định Danh (Unique Handle)
                                </label>
                                {isUsernameLocked ? (
                                    // Locked Username (Read-only display)
                                    <div className="bg-slate-950/30 border border-amber-500/20 rounded-lg p-4">
                                        <div className="flex items-center gap-3 mb-2">
                                            <AtSign className="w-5 h-5 text-amber-500" />
                                            <span className="text-lg font-sans text-amber-400">{username}</span>
                                        </div>
                                        <p className="text-xs text-slate-400 mb-1">
                                            Định danh của bạn đã được thiết lập và không thể thay đổi.
                                        </p>
                                        <p className="text-xs text-slate-600 font-sans">
                                            novest.com/u/{username}
                                        </p>
                                    </div>
                                ) : (
                                    // Editable Username (Can be changed once)
                                    <>
                                        <div className={`flex items-center bg-slate-950/50 border rounded-lg transition-all relative ${usernameAvailable === true ? "border-emerald-500/50 focus-within:border-emerald-500 focus-within:ring-1 focus-within:ring-emerald-500/20" :
                                            usernameAvailable === false ? "border-red-500/50 focus-within:border-red-500 focus-within:ring-1 focus-within:ring-red-500/20" :
                                                "border-white/10 focus-within:border-amber-500/50 focus-within:ring-1 focus-within:ring-amber-500/50"
                                            }`}>
                                            <div className="pl-3 flex items-center justify-center">
                                                <AtSign className="w-4 h-4 text-slate-500 pointer-events-none" />
                                            </div>
                                            <input
                                                id="username"
                                                type="text"
                                                value={username}
                                                onChange={(e) => setUsername(e.target.value)}
                                                disabled={isLoading}
                                                className="w-full bg-transparent border-none py-2.5 pl-3 pr-10 text-slate-200 focus:ring-0 placeholder:text-slate-600"
                                                placeholder="dao_huu_123"
                                            />
                                            <div className="absolute right-3 top-1/2 -translate-y-1/2 flex items-center pointer-events-none">
                                                {isCheckingUsername && (
                                                    <Loader2 className="w-4 h-4 text-amber-500 animate-spin" />
                                                )}
                                                {!isCheckingUsername && usernameAvailable === true && (
                                                    <CheckCircle2 className="w-4 h-4 text-emerald-500" />
                                                )}
                                                {!isCheckingUsername && usernameAvailable === false && (
                                                    <XCircle className="w-4 h-4 text-red-500" />
                                                )}
                                            </div>
                                        </div>
                                        <div className="flex justify-between items-start">
                                            <p className={`text-xs transition-colors ${usernameAvailable === true ? "text-emerald-400" :
                                                usernameAvailable === false ? "text-red-400" :
                                                    "text-slate-500"
                                                }`}>
                                                {usernameMessage || "Định danh duy nhất dùng cho URL trang cá nhân của bạn. Bạn chỉ có thể thay đổi một lần."}
                                            </p>
                                            <span className="text-xs text-slate-600 font-sans">
                                                novest.com/u/{username || "..."}
                                            </span>
                                        </div>
                                    </>
                                )}
                            </div>
                        </div>

                        {/* Birthday Section */}
                        <div className="space-y-4">
                            <h2 className="text-xl font-bold text-transparent bg-clip-text bg-linear-to-r from-amber-200 to-amber-400">Ngày Sinh</h2>
                            <div className="bg-slate-950/50 backdrop-blur-xs rounded-xl border border-white/10 p-6">
                                {isBirthdayLocked ? (
                                    // Locked Birthday (Read-only display)
                                    <div className="space-y-2">
                                        <div className="flex items-center gap-3">
                                            <span className="text-2xl">🎂</span>
                                            <span className="text-lg font-semibold text-amber-400">
                                                {savedBirthday && new Date(savedBirthday).toLocaleDateString('vi-VN', { day: 'numeric', month: 'long', year: 'numeric' })}
                                            </span>
                                        </div>
                                        <p className="text-xs text-slate-400">
                                            Ngày sinh của bạn đã được thiết lập và không thể thay đổi.
                                        </p>
                                        <p className="text-sm text-amber-400 flex items-center gap-2 mt-3">
                                            🎁 Novest sẽ gửi quà vào ngày sinh nhật của bạn!
                                        </p>
                                    </div>
                                ) : (
                                    // Editable Birthday (Can be set once)
                                    <>
                                        <div className="flex flex-wrap gap-3 mb-4">
                                            <select
                                                value={birthDay}
                                                onChange={(e) => setBirthDay(e.target.value)}
                                                className="bg-slate-900 border border-white/10 rounded-lg px-4 py-2.5 text-slate-200 focus:border-amber-500/50 focus:ring-1 focus:ring-amber-500/50 outline-none"
                                            >
                                                <option value="">Ngày</option>
                                                {Array.from({ length: 31 }, (_, i) => (
                                                    <option key={i + 1} value={String(i + 1).padStart(2, '0')}>{i + 1}</option>
                                                ))}
                                            </select>
                                            <select
                                                value={birthMonth}
                                                onChange={(e) => setBirthMonth(e.target.value)}
                                                className="bg-slate-900 border border-white/10 rounded-lg px-4 py-2.5 text-slate-200 focus:border-amber-500/50 focus:ring-1 focus:ring-amber-500/50 outline-none"
                                            >
                                                <option value="">Tháng</option>
                                                {[
                                                    "Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4",
                                                    "Tháng 5", "Tháng 6", "Tháng 7", "Tháng 8",
                                                    "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"
                                                ].map((month, i) => (
                                                    <option key={i + 1} value={String(i + 1).padStart(2, '0')}>{month}</option>
                                                ))}
                                            </select>
                                            <select
                                                value={birthYear}
                                                onChange={(e) => setBirthYear(e.target.value)}
                                                className="bg-slate-900 border border-white/10 rounded-lg px-4 py-2.5 text-slate-200 focus:border-amber-500/50 focus:ring-1 focus:ring-amber-500/50 outline-none"
                                            >
                                                <option value="">Năm</option>
                                                {Array.from({ length: 100 }, (_, i) => {
                                                    const year = new Date().getFullYear() - i;
                                                    return <option key={year} value={year}>{year}</option>;
                                                })}
                                            </select>
                                        </div>
                                        <p className="text-xs text-slate-500 mb-2">
                                            ⚠️ Bạn chỉ có thể đặt ngày sinh một lần duy nhất.
                                        </p>
                                        <p className="text-sm text-amber-400 flex items-center gap-2">
                                            🎁 Novest sẽ gửi quà vào ngày sinh nhật của bạn!
                                        </p>
                                    </>
                                )}
                            </div>
                        </div>

                        {/* Actions */}
                        <div className="pt-6 border-t border-white/5 flex items-center gap-4">
                            <button
                                type="submit"
                                disabled={isLoading || (usernameAvailable === false && username !== session.user.username)}
                                className="bg-linear-to-r from-amber-600 to-amber-500 hover:from-amber-500 hover:to-amber-400 text-slate-950 font-bold py-2.5 px-6 rounded-lg shadow-lg shadow-amber-500/20 transition-all active:scale-95 disabled:opacity-50 disabled:cursor-not-allowed flex items-center gap-2"
                            >
                                {isLoading ? <Loader2 className="w-4 h-4 animate-spin" /> : <Save className="w-4 h-4" />}
                                Lưu Thay Đổi
                            </button>
                            <button
                                type="button"
                                onClick={() => {
                                    setNickname(session.user.nickname || "");
                                    setUsername(session.user.username || "");
                                    setImage(session.user.image || "");
                                    setUsernameAvailable(null);
                                    setUsernameMessage("");
                                }}
                                disabled={isLoading}
                                className="px-6 py-2.5 rounded-lg border border-white/10 hover:bg-white/5 text-slate-300 transition-colors disabled:opacity-50"
                            >
                                Đặt Lại
                            </button>
                        </div>
                    </form>
                </div>
            </div>

            {/* Welcome Modal */}
            {
                showWelcome && (
                    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-sm">
                        <div className="bg-slate-900 border border-amber-500/20 rounded-2xl p-8 max-w-md w-full shadow-2xl relative overflow-hidden animate-in fade-in zoom-in duration-300">
                            <div className="absolute top-0 left-0 w-full h-1 bg-linear-to-r from-amber-500 to-emerald-500" />
                            <div className="text-center space-y-4">
                                <div className="w-16 h-16 bg-amber-500/10 rounded-full flex items-center justify-center mx-auto mb-4">
                                    <User className="w-8 h-8 text-amber-500" />
                                </div>
                                <h2 className="text-2xl font-bold text-white">Chào mừng đạo hữu!</h2>
                                <p className="text-slate-400">
                                    Chào mừng bạn đến với Novest. Hệ thống đã tự động tạo cho bạn một định danh.
                                    Bạn có thể thay đổi nó ngay bây giờ hoặc để sau.
                                </p>
                                <button
                                    onClick={() => setShowWelcome(false)}
                                    className="w-full bg-amber-500 hover:bg-amber-600 text-slate-950 font-bold py-3 rounded-lg transition-colors mt-4"
                                >
                                    Đã Hiểu, Để Ta Xem Xét
                                </button>
                            </div>
                        </div>
                    </div>
                )
            }
        </div >
    );
}
